# Generated by Django 5.0.4 on 2024-04-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_employee_image_remove_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='please provide number', max_length=200),
            preserve_default=False,
        ),
    ]
